
package hn.com.tigo.equipmentaccessoriesbilling.services.payupfrontservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AdapterException", targetNamespace = "http://task.cbs3.adapter.orchestrator.josm.tigo.com.hn/")
public class AdapterException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AdapterException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AdapterException_Exception(String message, AdapterException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AdapterException_Exception(String message, AdapterException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: hn.com.tigo.equipmentaccessoriesbilling.services.payupfrontservice.AdapterException
     */
    public AdapterException getFaultInfo() {
        return faultInfo;
    }

}
