
package hn.com.tigo.equipmentaccessoriesbilling.services.payupfrontservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CBS3ArPayUpFrontTaskService", targetNamespace = "http://task.cbs3.adapter.orchestrator.josm.tigo.com.hn/", wsdlLocation = "http://192.168.159.192:7010/CBS3ArPayUpFrontTask/CBS3ArPayUpFrontTaskService?WSDL")
public class CBS3ArPayUpFrontTaskService
    extends Service
{

    private final static URL CBS3ARPAYUPFRONTTASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException CBS3ARPAYUPFRONTTASKSERVICE_EXCEPTION;
    private final static QName CBS3ARPAYUPFRONTTASKSERVICE_QNAME = new QName("http://task.cbs3.adapter.orchestrator.josm.tigo.com.hn/", "CBS3ArPayUpFrontTaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.159.192:7010/CBS3ArPayUpFrontTask/CBS3ArPayUpFrontTaskService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBS3ARPAYUPFRONTTASKSERVICE_WSDL_LOCATION = url;
        CBS3ARPAYUPFRONTTASKSERVICE_EXCEPTION = e;
    }

    public CBS3ArPayUpFrontTaskService() {
        super(__getWsdlLocation(), CBS3ARPAYUPFRONTTASKSERVICE_QNAME);
    }

    public CBS3ArPayUpFrontTaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBS3ARPAYUPFRONTTASKSERVICE_QNAME, features);
    }

    public CBS3ArPayUpFrontTaskService(URL wsdlLocation) {
        super(wsdlLocation, CBS3ARPAYUPFRONTTASKSERVICE_QNAME);
    }

    public CBS3ArPayUpFrontTaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBS3ARPAYUPFRONTTASKSERVICE_QNAME, features);
    }

    public CBS3ArPayUpFrontTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBS3ArPayUpFrontTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CBS3ArPayUpFrontTask
     */
    @WebEndpoint(name = "CBS3ArPayUpFrontTaskPort")
    public CBS3ArPayUpFrontTask getCBS3ArPayUpFrontTaskPort() {
        return super.getPort(new QName("http://task.cbs3.adapter.orchestrator.josm.tigo.com.hn/", "CBS3ArPayUpFrontTaskPort"), CBS3ArPayUpFrontTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBS3ArPayUpFrontTask
     */
    @WebEndpoint(name = "CBS3ArPayUpFrontTaskPort")
    public CBS3ArPayUpFrontTask getCBS3ArPayUpFrontTaskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://task.cbs3.adapter.orchestrator.josm.tigo.com.hn/", "CBS3ArPayUpFrontTaskPort"), CBS3ArPayUpFrontTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBS3ARPAYUPFRONTTASKSERVICE_EXCEPTION!= null) {
            throw CBS3ARPAYUPFRONTTASKSERVICE_EXCEPTION;
        }
        return CBS3ARPAYUPFRONTTASKSERVICE_WSDL_LOCATION;
    }

}
