package hn.com.tigo.jteller.utils;

public class Contants {

	public static final String REQUEST_CUSTOMER_INFO= "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:task=\"http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/\" xmlns:v1=\"http://adapter.josm.tigo.com.hn/RequestType/V1\">\r\n"
			+ "   <soapenv:Header/>\r\n"
			+ "   <soapenv:Body>\r\n"
			+ "      <task:executeTask>\r\n"
			+ "         <!--Optional:-->\r\n"
			+ "         <arg0>\r\n"
			+ "            <v1:transactionId>?</v1:transactionId>\r\n"
			+ "            <!--Optional:-->\r\n"
			+ "            <v1:parameters>\r\n"
			+ "               <!--Zero or more repetitions:-->\r\n"
			+ "               <parameter>\r\n"
			+ "                  <name>JSON</name>\r\n"
			+ "                  <value>{\"queryObj\": {\r\n"
			+ "                  \"acctAccessCode\": {\r\n"
			+ "                  \"<TYPE>\": \"<VALUE>\",\r\n"
			+ "                  \"payType\": \"2\"\r\n"
			+ "                  }\r\n"
			+ "                  }\r\n"
			+ "                  }\r\n"
			+ "                  </value>\r\n"
			+ "               </parameter>\r\n"
			+ "            </v1:parameters>\r\n"
			+ "         </arg0>\r\n"
			+ "      </task:executeTask>\r\n"
			+ "   </soapenv:Body>\r\n"
			+ "</soapenv:Envelope>";
	
	public static final String REQUEST_INVOICE = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:task=\"http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/\" xmlns:v1=\"http://adapter.josm.tigo.com.hn/RequestType/V1\">\r\n"
			+ "   <soapenv:Header/>\r\n"
			+ "   <soapenv:Body>\r\n"
			+ "      <task:executeTask>\r\n"
			+ "         <!--Optional:-->\r\n"
			+ "         <arg0>\r\n"
			+ "            <v1:transactionId>?</v1:transactionId>\r\n"
			+ "            <!--Optional:-->\r\n"
			+ "            <v1:parameters>\r\n"
			+ "               <!--Zero or more repetitions:-->\r\n"
			+ "               <parameter>\r\n"
			+ "                  <name>JSON</name>\r\n"
			+ "                  <value> {\r\n"
			+ "  \"queryObj\": {\r\n"
			+ "   \"acctAccessCode\": {\r\n"
			+ "    \"accountCode\": \"<VALUE>\",\r\n"
			+ "    \"payType\":\"2\"\r\n"
			+ "   }\r\n"
			+ "  },\r\n"
			+ "  \"invoiceHeaderFilter\": {\r\n"
			+ "   \"status\":\"O\"\r\n"
			+ "  },\r\n"
			+ "  \"retrieveDetail\": \"1\",\r\n"
			+ "  \"totalRowNum\": \"100\",\r\n"
			+ "  \"beginRowNum\": \"0\",\r\n"
			+ "  \"fetchRowNum\": \"0\"\r\n"
			+ " }</value>\r\n"
			+ "               </parameter>\r\n"
			+ "            </v1:parameters>\r\n"
			+ "         </arg0>\r\n"
			+ "      </task:executeTask>\r\n"
			+ "   </soapenv:Body>\r\n"
			+ "</soapenv:Envelope>";
}
