
package hn.com.tigo.comodatos.services.soap.siebel.cbsquery.customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SiebelQueryCustomerTaskService", targetNamespace = "http://task.siebel.adapter.orchestrator.josm.tigo.com.hn/", wsdlLocation = "http://192.168.159.192:7010/SiebelQueryCustomerTask/SiebelQueryCustomerTaskService?wsdl")
public class SiebelQueryCustomerTaskService
    extends Service
{

    private final static URL SIEBELQUERYCUSTOMERTASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIEBELQUERYCUSTOMERTASKSERVICE_EXCEPTION;
    private final static QName SIEBELQUERYCUSTOMERTASKSERVICE_QNAME = new QName("http://task.siebel.adapter.orchestrator.josm.tigo.com.hn/", "SiebelQueryCustomerTaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.159.192:7010/SiebelQueryCustomerTask/SiebelQueryCustomerTaskService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIEBELQUERYCUSTOMERTASKSERVICE_WSDL_LOCATION = url;
        SIEBELQUERYCUSTOMERTASKSERVICE_EXCEPTION = e;
    }

    public SiebelQueryCustomerTaskService() {
        super(__getWsdlLocation(), SIEBELQUERYCUSTOMERTASKSERVICE_QNAME);
    }

    public SiebelQueryCustomerTaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIEBELQUERYCUSTOMERTASKSERVICE_QNAME, features);
    }

    public SiebelQueryCustomerTaskService(URL wsdlLocation) {
        super(wsdlLocation, SIEBELQUERYCUSTOMERTASKSERVICE_QNAME);
    }

    public SiebelQueryCustomerTaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIEBELQUERYCUSTOMERTASKSERVICE_QNAME, features);
    }

    public SiebelQueryCustomerTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiebelQueryCustomerTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiebelQueryCustomerTask
     */
    @WebEndpoint(name = "SiebelQueryCustomerTaskPort")
    public SiebelQueryCustomerTask getSiebelQueryCustomerTaskPort() {
        return super.getPort(new QName("http://task.siebel.adapter.orchestrator.josm.tigo.com.hn/", "SiebelQueryCustomerTaskPort"), SiebelQueryCustomerTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiebelQueryCustomerTask
     */
    @WebEndpoint(name = "SiebelQueryCustomerTaskPort")
    public SiebelQueryCustomerTask getSiebelQueryCustomerTaskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://task.siebel.adapter.orchestrator.josm.tigo.com.hn/", "SiebelQueryCustomerTaskPort"), SiebelQueryCustomerTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIEBELQUERYCUSTOMERTASKSERVICE_EXCEPTION!= null) {
            throw SIEBELQUERYCUSTOMERTASKSERVICE_EXCEPTION;
        }
        return SIEBELQUERYCUSTOMERTASKSERVICE_WSDL_LOCATION;
    }

}
