export type Buttons = 'add' | 'see' | 'edit' | 'emit';

export interface DropdownSettingsI{
    singleSelection?: boolean,
    text?: string,
    enableCheckAll?: boolean,
    selectAllText?: string,
    unSelectAllText?: string,
    enableSearchFilter?: boolean,
    enableFilterSelectAll?: boolean,
    filterSelectAllText?: string,
    filterUnSelectAllText?: string,
    maxHeight?: number,
    badgeShowLimit?: number,
    classes?: string,
    limitSelection?: number,
    disabled?: boolean,
    searchPlaceholderText?: string,
    groupBy?: string,
    selectGroup?: boolean,
    searchAutofocus?: boolean,
    labelKey?: string,
    primaryKey?: string,
    position?: string,
    noDataLabel?: string,
    searchBy?: [],
    lazyLoading?: boolean,
    showCheckbox?:  boolean,
    addNewItemOnFilter?: boolean,
    addNewButtonText?: string,
    escapeToClose?: boolean,
    autoPosition?: boolean,
    tagToBody?: boolean
}