
package hn.com.tigo.equipmentinsurance.services.exchangerate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BasicExchangeRatePort", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasicExchangeRatePort {


    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.CurrencyACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "AddCurrency")
    @WebResult(name = "CurrencyACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public CurrencyACKType addCurrency(
        @WebParam(name = "addCurrency", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        CurrencyType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.CurrencyACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "DeleteCurrency")
    @WebResult(name = "CurrencyACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public CurrencyACKType deleteCurrency(
        @WebParam(name = "deleteCurrency", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        CurrencyTypeS body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.CurrencyACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "ModifyCurrency")
    @WebResult(name = "CurrencyACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public CurrencyACKType modifyCurrency(
        @WebParam(name = "modifyCurrency", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        CurrencyType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.CurrencyType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "GetCurrency")
    @WebResult(name = "CurrencyResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public CurrencyType getCurrency(
        @WebParam(name = "getCurrency", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        CurrencyTypeS body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.ExchangeACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "AddExchange")
    @WebResult(name = "ExchangeACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public ExchangeACKType addExchange(
        @WebParam(name = "addExchange", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        ExchangeType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.ExchangeACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "DeleteExchange")
    @WebResult(name = "ExchangeACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public ExchangeACKType deleteExchange(
        @WebParam(name = "deleteExchange", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        ExchangeTypeD body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.ExchangeACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "ModifyExchange")
    @WebResult(name = "ExchangeACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public ExchangeACKType modifyExchange(
        @WebParam(name = "modifyExchange", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        ExchangeTypeM body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.exchangerate.ExchangeResponseType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "GetExchange")
    @WebResult(name = "ExchangeResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
    public ExchangeResponseType getExchange(
        @WebParam(name = "getExchange", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema", partName = "body")
        ExchangeTypeG body)
        throws MessageFaultMsg
    ;

}
