
package hn.com.tigo.selfconsumption.services.offeringinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CBSQueryOfferingInfoTaskService", targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", wsdlLocation = "http://192.168.159.192:7010/CBSQueryOfferingInfoTask/CBSQueryOfferingInfoTaskService?wsdl")
public class CBSQueryOfferingInfoTaskService
    extends Service
{

    private final static URL CBSQUERYOFFERINGINFOTASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException CBSQUERYOFFERINGINFOTASKSERVICE_EXCEPTION;
    private final static QName CBSQUERYOFFERINGINFOTASKSERVICE_QNAME = new QName("http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", "CBSQueryOfferingInfoTaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.159.192:7010/CBSQueryOfferingInfoTask/CBSQueryOfferingInfoTaskService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CBSQUERYOFFERINGINFOTASKSERVICE_WSDL_LOCATION = url;
        CBSQUERYOFFERINGINFOTASKSERVICE_EXCEPTION = e;
    }

    public CBSQueryOfferingInfoTaskService() {
        super(__getWsdlLocation(), CBSQUERYOFFERINGINFOTASKSERVICE_QNAME);
    }

    public CBSQueryOfferingInfoTaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CBSQUERYOFFERINGINFOTASKSERVICE_QNAME, features);
    }

    public CBSQueryOfferingInfoTaskService(URL wsdlLocation) {
        super(wsdlLocation, CBSQUERYOFFERINGINFOTASKSERVICE_QNAME);
    }

    public CBSQueryOfferingInfoTaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CBSQUERYOFFERINGINFOTASKSERVICE_QNAME, features);
    }

    public CBSQueryOfferingInfoTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBSQueryOfferingInfoTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CBSQueryOfferingInfoTask
     */
    @WebEndpoint(name = "CBSQueryOfferingInfoTaskPort")
    public CBSQueryOfferingInfoTask getCBSQueryOfferingInfoTaskPort() {
        return super.getPort(new QName("http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", "CBSQueryOfferingInfoTaskPort"), CBSQueryOfferingInfoTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBSQueryOfferingInfoTask
     */
    @WebEndpoint(name = "CBSQueryOfferingInfoTaskPort")
    public CBSQueryOfferingInfoTask getCBSQueryOfferingInfoTaskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", "CBSQueryOfferingInfoTaskPort"), CBSQueryOfferingInfoTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CBSQUERYOFFERINGINFOTASKSERVICE_EXCEPTION!= null) {
            throw CBSQUERYOFFERINGINFOTASKSERVICE_EXCEPTION;
        }
        return CBSQUERYOFFERINGINFOTASKSERVICE_WSDL_LOCATION;
    }

}
