
package hn.com.tigo.equipmentinsurance.services.exchangerate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicExchangeRateService", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1", wsdlLocation = "http://192.168.161.61:7003/ExchangeRate-web/BasicExchangeRateService?wsdl")
public class BasicExchangeRateService
    extends Service
{

    private final static URL BASICEXCHANGERATESERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICEXCHANGERATESERVICE_EXCEPTION;
    private final static QName BASICEXCHANGERATESERVICE_QNAME = new QName("http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1", "BasicExchangeRateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.161.61:7003/ExchangeRate-web/BasicExchangeRateService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICEXCHANGERATESERVICE_WSDL_LOCATION = url;
        BASICEXCHANGERATESERVICE_EXCEPTION = e;
    }

    public BasicExchangeRateService() {
        super(__getWsdlLocation(), BASICEXCHANGERATESERVICE_QNAME);
    }

    public BasicExchangeRateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICEXCHANGERATESERVICE_QNAME, features);
    }

    public BasicExchangeRateService(URL wsdlLocation) {
        super(wsdlLocation, BASICEXCHANGERATESERVICE_QNAME);
    }

    public BasicExchangeRateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICEXCHANGERATESERVICE_QNAME, features);
    }

    public BasicExchangeRateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicExchangeRateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BasicExchangeRatePort
     */
    @WebEndpoint(name = "BasicExchangeRatePort")
    public BasicExchangeRatePort getBasicExchangeRatePort() {
        return super.getPort(new QName("http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1", "BasicExchangeRatePort"), BasicExchangeRatePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicExchangeRatePort
     */
    @WebEndpoint(name = "BasicExchangeRatePort")
    public BasicExchangeRatePort getBasicExchangeRatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1", "BasicExchangeRatePort"), BasicExchangeRatePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICEXCHANGERATESERVICE_EXCEPTION!= null) {
            throw BASICEXCHANGERATESERVICE_EXCEPTION;
        }
        return BASICEXCHANGERATESERVICE_WSDL_LOCATION;
    }

}
