-- PARAMETER CONFIGURATION TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_CONFIG_PARAMETERS" 
   (	"ID" NUMBER, 
	"ID_APPLICATION" NUMBER, 
	"PARAMETER_TYPE" VARCHAR2(100 BYTE), 
	"PARAMETER_NAME" VARCHAR2(100 BYTE), 
	"PARAMETER_DESCRIPTION" VARCHAR2(500 BYTE), 
	"PARAMETER_VALUE" VARCHAR2(500 BYTE), 
	"STATE_CODE" NUMBER, 
	"CREATED" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;
  
------------------------------------------------------------------------------

  -- INSERT SE_CONFIG_PARAMETERS
  
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (20,2604,'EXCHANGE_RATE_SERVICE','ENDPOINT_EXCHANGE_RATE','URL del servicio ExchangeRate','http://192.168.161.61:7003/ExchangeRate-web/BasicExchangeRateService',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (21,30410,'RESERVE_SERIAL_BSIM','RESERVE_SERIAL_ENDPOINT','Parametro','http://uat.bsim.tigo.com.hn:30410/api/bsim-operations-service/v1/operations/reserveSerialNumbers',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (22,999,'CALCULO_INVOICE','PERCENTAGE_TAX','Parametro utilizado para calcular el impuesto de las facturas','15',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (23,2604,'EXCHANGE_RATE_SERVICE','USER_EXCHANGE_RATE','Usuario','RFAC_CBS',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (24,2604,'EXCHANGE_RATE_SERVICE','PASS_EXCHANGE_RATE','Password utilizado para la seguridad del servicio','Tig0_CBS#2021',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (1,1000,'INVENTORY_TYPE','INVENTORY_TYPE_PARAM','Paramentro utilizado para la creacion de reclamo por seguro','S',1,to_date('21/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (2,1000,'STATUS_COLGANTE','STATUS_COLGANTE_PARAM','Paramentro utilizado para la creacion de reclamo por seguro','P',1,to_date('21/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (3,1000,'STATUS_PHONE','STATUS_PHONE_PARAM','Paramentro utilizado para la creacion de reclamo por seguro','A',1,to_date('21/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (11,30410,'AUTHENTICATION_BSIM','ENDPOINT_PROXY_REALEASE_SERIAL_NUMBER','Parametro utilizado para consumir el servicio de liberación número de series de bsim.','/api/bsim-operations-service/v1/operations/releaseSerialNumbers',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (12,30410,'AUTHENTICATION_BSIM','ENDPOINT_PROXY_AUTH','Parametro utilizado para consumir el servicio de autenticacion de bsim.','/api/auth-server/auth-server/oauth/token',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (13,30410,'AUTHENTICATION_BSIM','PASSWORD','Parametro utilizado para consumir el servicio de autenticacion de bsim.','imt6HkszyVOtBgqPo4DIt9wc54LdZD1Ul0wiKGIvKY7VMNZTZ9/VFbvITFV%2BLptn%2B/F8YX3AFsWppV0DSigfw2Y%2Bch5p0fbWgchatNPI41/rz5xmWSgXipmzZVdZClj%2B%2BYfICJjRbgOE0pFqUj4x4%2B8/ONg/RDtQ6TuSoFSKqr1BBjeepczP9J3UoK6qrzz4TKSU/S8EPXrW6rxDrC/Tbz4gtfep1iUwuNaPyaOGYKhgdS6ZteyBhW232et%2BLuis0DogJLg0uo2GeKTf5KEDbAj8zqep%2BhA037%2BMdoWvSNZl4ydvUUOPdEgJt5BmNZ5Bui3ngR6DU7sXkX0yFvAgjQ==',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (14,30410,'AUTHENTICATION_BSIM','USERNAME','Parametro utilizado para consumir el servicio de autenticacion de bsim.','BSIM',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (15,30410,'AUTHENTICATION_BSIM','CLIENT_SECRET','Parametro utilizado para consumir el servicio de autenticacion de bsim.','secret',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (16,30410,'AUTHENTICATION_BSIM','CLIENT_ID','Parametro utilizado para consumir el servicio de autenticacion de bsim.','client',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (17,30410,'AUTHENTICATION_BSIM','GRANT_TYPE','Parametro utilizado para consumir el servicio de autenticacion de bsim.','password',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (18,30410,'AUTHENTICATION_BSIM','ENDPOINT','Parametro utilizado para consumir el servicio de autenticacion de bsim.','http://uat.bsim.tigo.com.hn:30410/api/auth-server/auth-server/oauth/token',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (19,30410,'SERIAL_NUMBERS_QUERY_BSIM','SERIAL_NUMBERS_QUERY_ENDPOINT','Parametro utilizado para consumir el servicio serial numbers query de bsim.','http://uat.bsim.tigo.com.hn:30410/api/bsim-query-service/v1/queries/serialNumbersQuery',1,to_date('27/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (4,1000,'EXISTENCES_TYPE','EXISTENCES_TYPE_PARAM','Parametro utilizado para consumir el servicio de las existencias.','inventory',1,to_date('21/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (5,1000,'EXISTENCES_EQUIPMENT_LINE','EXISTENCES_EQUIPMENT_LINE_PARAM','Parametro utilizado para consumir el servicio de las existencias.','TEL',1,to_date('21/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (25,1000,'INSURANCE_PREMIUMS_PARAM','INSURANCE_PREMIUMS','Parametro utilizado para las primas de seguro','0',1,to_date('04/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (6,1000,'DEDUCTIBLE_MODEL','DEDUCTIBLE_MODEL_PARAM','Parametro utilizado para crear el detalle de la factura por reclamo de seguros.','198',1,to_date('26/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (7,1000,'DEDUCTIBLE_DESCRIPTION','DEDUCTIBLE_DESCRIPTION_PARAM','Parametro utilizado para crear el detalle de la factura por reclamo de seguros.','DEDUCIBLE (ROBO)',1,to_date('26/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (8,1000,'INSURANCE_PREMIUM_MODEL','INSURANCE_PREMIUM_MODEL_PARAM','Parametro','364',1,to_date('26/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (9,1000,'INSURANCE_PREMIUM_DESCRIPTION','INSURANCE_PREMIUM_DESCRIPTION_PARAM','Parametro','PRIMA DE SEGURO',1,to_date('26/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (10,1000,'CHANNEL','CHANNEL_PARAM','Parametro','3',1,to_date('26/11/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (26,1000,'BLOCK_DAYS','BLOCK_DAYS_PARAM','Parametro utilizado para validar los dias de bloqueo que tiene una IMEI.','50',1,to_date('11/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (27,7010,'EXECUTE_ORDER_SERVICE','EXECUTE_ORDER_ENPOINT','Parametro utilizado para obtener la mora.','http://192.168.159.192:7010/ExecuteOrder/ExecuteOrderService',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (28,7010,'EXECUTE_ORDER_SERVICE','CHANNEL_ID','Parametro utilizado para obtener la mora.','102',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (29,7010,'EXECUTE_ORDER_SERVICE','SUBSCRIBER_ID','Parametro utilizado para obtener la mora.','9000267402',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (30,7010,'EXECUTE_ORDER_SERVICE','PRODUCT_ID','Parametro utilizado para obtener la mora.','9002266',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (31,7010,'EXECUTE_ORDER_SERVICE','QUANTITY','Parametro utilizado para obtener la mora.','1',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (32,7010,'EXECUTE_ORDER_SERVICE','ROOT_ASSET','Parametro utilizado para obtener la mora.','TELEFONIA MOVIL',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (33,7010,'EXECUTE_ORDER_SERVICE','TIPO_CONSULTA','Parametro utilizado para obtener la mora.','OBLIGACIONES',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (34,7010,'EXECUTE_ORDER_SERVICE','CLAUSULA_PERMANENCIA','Parametro utilizado para obtener la mora.','0',1,to_date('16/12/24','DD/MM/RR'));
Insert into ASDCMMSSI.SE_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_TYPE,PARAMETER_NAME,PARAMETER_DESCRIPTION,PARAMETER_VALUE,STATE_CODE,CREATED) values (35,7010,'EXECUTE_ORDER_SERVICE','TYPE_ACCESS_CODE','Parametro utilizado para obtener la mora.','AccountKey',1,to_date('16/12/24','DD/MM/RR'));

------------------------------------------------------------------------------

-- REASONS TABLE:

 CREATE TABLE "ASDCMMSSI"."SE_REASONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REASON" VARCHAR2(150 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"STATUS" NUMBER, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_REASONS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_SE_REASONS" 
BEFORE INSERT ON SE_REASONS
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_REASONS.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;

/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_SE_REASONS" ENABLE;

------------------------------------------------------------------------------

-- LOGS TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_LOGS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"TYPE_ERROR" NUMBER(*,0), 
	"MESSAGE" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"REFERENCE" VARCHAR2(100 BYTE), 
	"SRT" CLOB, 
	"URL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_ASDCMMSSI" 
 LOB ("SRT") STORE AS BASICFILE (
  TABLESPACE "TBS_ASDCMMSSI" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_LOGS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_SE_LOGS" 
BEFORE INSERT ON SE_LOGS
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_LOGS.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_SE_LOGS" ENABLE;

------------------------------------------------------------------------------

-- ERROR TYPE CONTROL TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_ERROR_TYPE_CONTROL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TYPE_ERROR" NUMBER, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATED" DATE DEFAULT sysdate NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_ERROR_TYPE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_SE_ERROR_TYPE" 
BEFORE INSERT ON SE_ERROR_TYPE_CONTROL
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_ERROR_TYPE.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_SE_ERROR_TYPE" ENABLE;


------------------------------------------------------------------------------

-- PRICE MASTER TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_PRICE_MASTER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"INVENTORY_TYPE" NVARCHAR2(1), 
	"MODEL" NVARCHAR2(6), 
	"BASE_COST" NUMBER(13,2), 
	"FACTOR_CODE" NUMBER(3,0), 
	"PRICE" NUMBER(13,2), 
	"USER_CREATED" NVARCHAR2(10), 
	"SCREEN" NVARCHAR2(10), 
	"CREATED_DATE" DATE, 
	"CURRENCY" NVARCHAR2(10), 
	"LEMPIRAS_PRICE" NUMBER(13,2), 
	"TEMPORARY_COST" NUMBER(13,2), 
	 CONSTRAINT "SE_PRICE_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_INVENTORY_TYPE_MODEL" ON "ASDCMMSSI"."SE_PRICE_MASTER" ("INVENTORY_TYPE", "MODEL") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_PRICE_MASTER START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_PRICE_MASTER" 
BEFORE INSERT ON SE_PRICE_MASTER
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_PRICE_MASTER.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_PRICE_MASTER" ENABLE;


------------------------------------------------------------------------------

-- PREMIUM RATES TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_PREMIUM_RATES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MODEL" VARCHAR2(100 BYTE), 
	"DEVICE_VALUE" VARCHAR2(100 BYTE), 
	"MONTHLY_PREMIUM" NUMBER, 
	"STATUS" NUMBER, 
	"CREATED" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "PK_ID_PREMIUM_RATES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_PREMIUM_RATE_MODEL" ON "ASDCMMSSI"."SE_PREMIUM_RATES" ("MODEL") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_PREMIUM_RATES START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_PREMIUM_RATES" 
BEFORE INSERT ON SE_PREMIUM_RATES
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_PREMIUM_RATES.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_PREMIUM_RATES" ENABLE;



------------------------------------------------------------------------------

-- INSURANCE RATES MODEL TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_INSURANCE_RATES_MODEL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"EFFECTIVE_DATE" DATE, 
	"PERIOD_NUMBER" NUMBER, 
	"VALUE_FROM" NUMBER(7,2), 
	"VALUE_UP" NUMBER(7,2), 
	"MONTHLY_FEE" NUMBER(7,2), 
	"TEXT_COVERAGE" NVARCHAR2(80), 
	"MODEL" NVARCHAR2(6), 
	 CONSTRAINT "SE_INSURANCE_RATES_MODEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_RATES_MODEL" ON "ASDCMMSSI"."SE_INSURANCE_RATES_MODEL" ("MODEL") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_INSURANCE_RATES START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_INSURANCE_RATES" 
BEFORE INSERT ON "SE_INSURANCE_RATES_MODEL"
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_INSURANCE_RATES.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_INSURANCE_RATES" ENABLE;


------------------------------------------------------------------------------

-- DEDUCTIBLE RATES TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_DEDUCTIBLE_RATES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MODEL" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"FIRST_CLAIM" VARCHAR2(100 BYTE), 
	"SECOND_CLAIM" VARCHAR2(100 BYTE), 
	"THIRD_CLAIM" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER, 
	"CREATED" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"REASON_ID" NUMBER, 
	 CONSTRAINT "PK_ID_DEDUCTIBLE_RATES" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_MODEL" ON "ASDCMMSSI"."SE_DEDUCTIBLE_RATES" ("MODEL") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_DEDUCTIBLE_RATES START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_DEDUCTIBLE_RATES" 
BEFORE INSERT ON SE_DEDUCTIBLE_RATES
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_DEDUCTIBLE_RATES.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_DEDUCTIBLE_RATES" ENABLE;



------------------------------------------------------------------------------

-- INSURANCE CLAIM TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_INSURANCE_CLAIM" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ACCOUNT" NVARCHAR2(30), 
	"SERVICE_ACCOUNT" NVARCHAR2(30), 
	"BILLING_ACCOUNT" NVARCHAR2(30), 
	"PHONE" NVARCHAR2(12), 
	"PHONE_STATUS" NVARCHAR2(1), 
	"CLIENT_TYPE" NVARCHAR2(3), 
	"ACTUAL_PRICE" NUMBER(13,2), 
	"ACTUAL_ESN" NVARCHAR2(15), 
	"ACTUAL_MODEL" NVARCHAR2(6), 
	"ACTUAL_INV_TYPE" NVARCHAR2(1), 
	"REASON_CLAIM" NVARCHAR2(20), 
	"NEW_ESN" NVARCHAR2(15), 
	"NEW_MODEL" NVARCHAR2(6), 
	"NEW_INV_TYPE" NVARCHAR2(1), 
	"USER_CREATE" NVARCHAR2(50) NOT NULL ENABLE, 
	"DATE_CREATE" DATE NOT NULL ENABLE, 
	"USER_RESOLUTION" NVARCHAR2(50), 
	"DATE_RESOLUTION" DATE, 
	"INVOICE_TYPE" NVARCHAR2(3), 
	"INVOICE_LETTER" NVARCHAR2(1), 
	"INVOICE_NUMBER" NUMBER(8,0), 
	"BRANCH_ANNEX" NUMBER(10,0), 
	"STATUS_CLAIM" NVARCHAR2(1), 
	"OBSERVATIONS" NVARCHAR2(300), 
	"INSURANCE_PREMIUM" NUMBER, 
	"DEDUCTIBLE" NUMBER, 
	"WAREHOUSE" VARCHAR2(100 BYTE), 
	"BANDIT" VARCHAR2(50 BYTE), 
	"NEW_MODEL_DESCRIPTION" VARCHAR2(250 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(250 BYTE), 
	"WORKSHOP_ORDER_NUMBER" VARCHAR2(100 BYTE), 
	"PRICE_ADJUSTMENT" NUMBER, 
	"ADJUSTMENT_PREMIUMS" NUMBER, 
	 CONSTRAINT "SE_INSURANCE_CLAIM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_ESN_CLAIM" ON "ASDCMMSSI"."SE_INSURANCE_CLAIM" ("ACTUAL_ESN") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_PHONE_CLAIM" ON "ASDCMMSSI"."SE_INSURANCE_CLAIM" ("PHONE") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_SE_INSURANCE_CLAIM START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_INSURANCE_CLAIM" 
BEFORE INSERT ON SE_INSURANCE_CLAIM
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_SE_INSURANCE_CLAIM.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_INSURANCE_CLAIM" ENABLE;


------------------------------------------------------------------------------

-- EQUIPMENT INSURANCE CONTROL TABLE:

  CREATE TABLE "ASDCMMSSI"."SE_EQUIPMENT_INSURANCE_CONTROL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_CODE" NVARCHAR2(5), 
	"USER_AS" NVARCHAR2(10), 
	"DATE_CONSULTATION" DATE DEFAULT NULL NOT NULL ENABLE, 
	"CUSTOMER_ACCOUNT" NVARCHAR2(30), 
	"SERVICE_ACCOUNT" NVARCHAR2(30), 
	"BILLING_ACCOUNT" NVARCHAR2(30), 
	"PHONE_NUMBER" NVARCHAR2(12), 
	"EQUIPMENT_MODEL" NVARCHAR2(6), 
	"ESN" NVARCHAR2(15), 
	"ORIGIN_AS" NVARCHAR2(1), 
	"INVENTORY_TYPE_AS" NVARCHAR2(1), 
	"ORIGIN_TYPE_AS" NVARCHAR2(1), 
	"DATE_CONTRACT" DATE DEFAULT NULL, 
	"START_DATE" DATE DEFAULT NULL NOT NULL ENABLE, 
	"END_DATE" DATE DEFAULT NULL NOT NULL ENABLE, 
	"DATE_INCLUSION" DATE DEFAULT NULL NOT NULL ENABLE, 
	"INSURANCE_RATE" NUMBER(9,2), 
	"PERIOD" NUMBER(3,0), 
	"INSURANCE_RATE_2" NUMBER(9,2), 
	"PERIOD_2" NUMBER(3,0), 
	"INSURANCE_RATE_3" NUMBER(9,2), 
	"PERIOD_3" NUMBER(3,0), 
	"INSURANCE_STATUS" NUMBER, 
	"SUBSCRIBER" NVARCHAR2(30), 
	"TRAMA" NVARCHAR2(2000), 
	 CONSTRAINT "SE_EQUIPMENT_INSURANCE_CON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_ESN_CONTROL" ON "ASDCMMSSI"."SE_EQUIPMENT_INSURANCE_CONTROL" ("ESN") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

  CREATE INDEX "ASDCMMSSI"."IDX_PHONE_NUMBER" ON "ASDCMMSSI"."SE_EQUIPMENT_INSURANCE_CONTROL" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

-- Creacion Secuencia y Trigger:

CREATE SEQUENCE ASDCMMSSI.SQ_EQUIPMENT_INSURANCE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."INCREMENTA_EQUIPMENT_INSURANCE" 
BEFORE INSERT ON SE_EQUIPMENT_INSURANCE_CONTROL
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_EQUIPMENT_INSURANCE.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;

/
ALTER TRIGGER "ASDCMMSSI"."INCREMENTA_EQUIPMENT_INSURANCE" ENABLE;



