-- PARAMETER CONFIGURATION TABLE:

  CREATE TABLE "ASDCMMSSI"."CMD_CONFIG_PARAMETERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_APPLICATION" NUMBER, 
	"PARAMETER_NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"VALUE" CLOB, 
	"CREATED" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "CMD_CONFIG_PARAM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" 
 LOB ("VALUE") STORE AS BASICFILE (
  TABLESPACE "TBS_ASDCMMSSI" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

------------------------------------------------------------------------------

--Creacion Secuencia y Trigger:
CREATE SEQUENCE ASDCMMSSI.SQ_CONFIG_PARAMETERS START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE OR REPLACE TRIGGER "ASDCMMSSI"."CMD_CONFIG_PARAMETERS_TRG" 
BEFORE INSERT ON CMD_CONFIG_PARAMETERS
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT SQ_CONFIG_PARAMETERS.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."CMD_CONFIG_PARAMETERS_TRG" ENABLE;

------------------------------------------------------------------------------
  -- INSERT CMD_CONFIG_PARAMETERS
  
Insert into ASDCMMSSI.CMD_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_NAME,DESCRIPTION,CREATED) values (3,4462,'MOORING_HOURS','Es la cantidad de horas que el usuario tiene disponible para amarrar o desamarrar suscriptores',to_date('12/06/24','DD/MM/RR'));
Insert into ASDCMMSSI.CMD_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_NAME,DESCRIPTION,CREATED) values (1,1000,'MAXLNVAC','MÁXIMO LÍNEA PARA UNIFICAR LOS DESCUENTOS VAC',to_date('07/02/24','DD/MM/RR'));
Insert into ASDCMMSSI.CMD_CONFIG_PARAMETERS (ID,ID_APPLICATION,PARAMETER_NAME,DESCRIPTION,CREATED) values (2,4462,'APVTC','APVTC = ALLOW_PERMISSION_VALIDATION_TO_CANCEL
INDICA SI SE SOLICITA AL USUARIO EL PERMISO PARA CANCELAR EL COMODATO, 0 = NO Y 1 = SI ',to_date('20/02/24','DD/MM/RR'));

--------------------------------------------------------------------------------


-- CANCELLATION PERMISSION TABLE:

  CREATE TABLE "ASDCMMSSI"."CMD_CANCELLATION_PERMISSION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"PERMIT_STATUS" VARCHAR2(1 BYTE), 
	"CREATED" DATE DEFAULT sysdate, 
	 CONSTRAINT "CMD_CANCELLATION_PERMISSION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------

--Creacion Secuencia y Trigger:
CREATE SEQUENCE ASDCMMSSI.CMD_CANCEL_PERMISSION_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE OR REPLACE TRIGGER "ASDCMMSSI"."CMD_CANCEL_PERMISSION_TRG" 
BEFORE INSERT ON CMD_CANCELLATION_PERMISSION
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT CMD_CANCEL_PERMISSION_SEQ.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."CMD_CANCEL_PERMISSION_TRG" ENABLE;

------------------------------------------------------------------------------

-- CONTROL CANCELLATION TABLE:

  CREATE TABLE "ASDCMMSSI"."CMD_CONTROL_CANCELLATION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_REFERENCE" NUMBER, 
	"DESCRIPTION" CLOB, 
	"CANCELLATION_USER" VARCHAR2(50 BYTE), 
	"CREATED" DATE DEFAULT sysdate, 
	 CONSTRAINT "CMD_CONTROL_CANCELLATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "TBS_ASDCMMSSI" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

------------------------------------------------------------------------------

--Creacion Secuencia y Trigger:
CREATE SEQUENCE ASDCMMSSI.CMD_CONTROL_CANCELLATION_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

  CREATE OR REPLACE TRIGGER "ASDCMMSSI"."CMD_CONTROL_CANCELLATION_TRG" 
BEFORE INSERT ON CMD_CONTROL_CANCELLATION
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE VALOR NUMBER := 0;
BEGIN
SELECT CMD_CONTROL_CANCELLATION_SEQ.NEXTVAL INTO VALOR FROM DUAL;
:NEW.ID := VALOR;
END;
/
ALTER TRIGGER "ASDCMMSSI"."CMD_CONTROL_CANCELLATION_TRG" ENABLE;

------------------------------------------------------------------------------

-- MOORING BILLING TABLE:

  CREATE TABLE "ASDCMMSSI"."CMD_MOORING_BILLING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CORRELATIVE_CMD" NUMBER NOT NULL ENABLE, 
	"CORRELATIVE_MOORING_CMD" NUMBER NOT NULL ENABLE, 
	"SUBSCRIBER_ID" VARCHAR2(30 BYTE), 
	"MONTHS_OF_PERMANENCE" NUMBER, 
	"CMD_STATUS" VARCHAR2(1 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"SUPERVISOR_USER" VARCHAR2(50 BYTE), 
	"USER_MOORING" VARCHAR2(50 BYTE), 
	"USER_CANCELLED" VARCHAR2(50 BYTE), 
	"DATE_OF_ADMISSION" DATE, 
	"DUE_DATE" DATE, 
	"INVOICE_LOCATION" NUMBER, 
	"INVOICE_SUBLOCITY" NUMBER, 
	"INVOICE_TYPE" VARCHAR2(3 BYTE), 
	"INVOICE_READING" VARCHAR2(1 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(50 BYTE), 
	"INVENTORY_TYPE" VARCHAR2(1 BYTE), 
	"INVENTORY_MODEL" VARCHAR2(6 BYTE), 
	"TEAM_SERIES" VARCHAR2(25 BYTE), 
	"PHONE_COST" NUMBER(13,2), 
	"PHONE_DISCOUNT" NUMBER(13,2), 
	"MOORING" NUMBER, 
	"PROMOTION" VARCHAR2(100 BYTE), 
	"TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"CUSTOMER_ACCOUNT" VARCHAR2(30 BYTE), 
	"SERVICE_ACCOUNT" VARCHAR2(30 BYTE), 
	"BILLING_ACCOUNT" VARCHAR2(30 BYTE), 
	"OBSERVATIONS" VARCHAR2(500 BYTE), 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"VAC" NUMBER(13,2), 
	 CONSTRAINT "CMD_MOORING_BILLING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI";

------------------------------------------------------------------------------

-- Creacion Secuencia:

CREATE SEQUENCE  "ASDCMMSSI"."CMD_MOORING_BILLING_SEQ"  MINVALUE 1 MAXVALUE 6000000 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

------------------------------------------------------------------------------

-- MOORING TABLE:

  CREATE TABLE "ASDCMMSSI"."CMD_MOORING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_MOORING_BILLING" NUMBER NOT NULL ENABLE, 
	"CUSTOMER_ACCOUNT" VARCHAR2(30 BYTE), 
	"BILLING_ACCOUNT" VARCHAR2(30 BYTE), 
	"SUBSCRIBER_ID" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"DATE_OF_ENTRY" DATE, 
	"CHECK_IN_TIME" VARCHAR2(10 BYTE), 
	"UNMOORING_USER" VARCHAR2(50 BYTE), 
	"UNMOORING_DATE" DATE, 
	"MOORING_STATUS" NUMBER, 
	"CREATED" DATE DEFAULT sysdate, 
	 CONSTRAINT "CMD_MOORING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 255 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;
  
------------------------------------------------------------------------------  
  -- Creacion Secuencia:
  
  CREATE SEQUENCE  "ASDCMMSSI"."CMD_MOORING_SEQ"  MINVALUE 1 MAXVALUE 6000000 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
  
 
 ------------------------------------------------------------------------------

-- PROMOTIONS TABLE: 

    CREATE TABLE "ASDCMMSSI"."CMD_PROMOTIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROMOTION_CODE" VARCHAR2(50 BYTE), 
	"MODEL_CODE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"CORPORATE" VARCHAR2(50 BYTE), 
	"PERMANENT_VALIDITY" VARCHAR2(50 BYTE), 
	"START_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"END_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;

------------------------------------------------------------------------------  
  -- Creacion Secuencia:
  
   CREATE SEQUENCE  "ASDCMMSSI"."SQ_CMD_PROMOTIONS"  MINVALUE 1 MAXVALUE 6000000 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   
 ------------------------------------------------------------------------------
   
 -- PROMOTIONS DETAILS TABLE:   
   
     CREATE TABLE "ASDCMMSSI"."CMD_PROMOTIONS_DETAILS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_PROMOTION" NUMBER, 
	"PROMOTION_CODE" VARCHAR2(50 BYTE), 
	"MODEL_CODE" VARCHAR2(50 BYTE), 
	"PLAN_VALUE" NUMBER(13,2), 
	"MONTHS_PERMANENCE" NUMBER(2,0), 
	"SUBSIDY_FUND" NUMBER(13,2), 
	"ADDITIONAL_SUBSIDY" NUMBER(13,2), 
	"INSTITUTIONAL_FUNDS" NUMBER(13,2), 
	"COOPS_FUND" NUMBER(13,2), 
	"STATUS" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 255 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_ASDCMMSSI" ;
  
  ------------------------------------------------------------------------------  
  -- Creacion Secuencia:
  
   CREATE SEQUENCE  "ASDCMMSSI"."SQ_PROMOTIONS_DETAILS"  MINVALUE 1 MAXVALUE 6000000 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   
 ------------------------------------------------------------------------------
   
