
package hn.com.tigo.equipmentaccessoriesbilling.services.exchangerate;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MessageFault", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/ExchangeRate/v1/schema")
public class MessageFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorsType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MessageFaultMsg(String message, ErrorsType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MessageFaultMsg(String message, ErrorsType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: hn.com.tigo.equipmentaccessoriesbilling.services.exchangerate.ErrorsType
     */
    public ErrorsType getFaultInfo() {
        return faultInfo;
    }

}
