
package hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicVoucherService", targetNamespace = "http://v1.voucher.service.electronicbilling.tigo.com/", wsdlLocation = "http://192.168.78.25:7016/VouchersWs/BasicVoucherService?wsdl")
public class BasicVoucherService
    extends Service
{

    private final static URL BASICVOUCHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICVOUCHERSERVICE_EXCEPTION;
    private final static QName BASICVOUCHERSERVICE_QNAME = new QName("http://v1.voucher.service.electronicbilling.tigo.com/", "BasicVoucherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.78.25:7016/VouchersWs/BasicVoucherService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICVOUCHERSERVICE_WSDL_LOCATION = url;
        BASICVOUCHERSERVICE_EXCEPTION = e;
    }

    public BasicVoucherService() {
        super(__getWsdlLocation(), BASICVOUCHERSERVICE_QNAME);
    }

    public BasicVoucherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICVOUCHERSERVICE_QNAME, features);
    }

    public BasicVoucherService(URL wsdlLocation) {
        super(wsdlLocation, BASICVOUCHERSERVICE_QNAME);
    }

    public BasicVoucherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICVOUCHERSERVICE_QNAME, features);
    }

    public BasicVoucherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicVoucherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BasicVoucherPort
     */
    @WebEndpoint(name = "BasicVoucherService")
    public BasicVoucherPort getBasicVoucherService() {
        return super.getPort(new QName("http://v1.voucher.service.electronicbilling.tigo.com/", "BasicVoucherService"), BasicVoucherPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicVoucherPort
     */
    @WebEndpoint(name = "BasicVoucherService")
    public BasicVoucherPort getBasicVoucherService(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.voucher.service.electronicbilling.tigo.com/", "BasicVoucherService"), BasicVoucherPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICVOUCHERSERVICE_EXCEPTION!= null) {
            throw BASICVOUCHERSERVICE_EXCEPTION;
        }
        return BASICVOUCHERSERVICE_WSDL_LOCATION;
    }

}
