FROM eclipse-temurin:8-jdk-alpine
ENV TZ=America/Tegucigalpa
COPY ./target/EquipmentInsurance-1.0.0.jar EquipmentInsurance-1.0.0.jar
EXPOSE 4445
ENTRYPOINT ["java","-jar","/EquipmentInsurance-1.0.0.jar"]