
package hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BasicVoucherPort", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasicVoucherPort {


    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherResponseType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "AddVoucher", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/AddVoucher")
    @WebResult(name = "VoucherResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/AddVoucher", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/AddVoucherResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/AddVoucher/Fault/MessageFaultMsg")
    })
    public VoucherResponseType addVoucher(
        @WebParam(name = "addVoucher", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        VoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "Noop", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/Noop")
    @WebResult(name = "Alive", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema")
    @RequestWrapper(localName = "Noop", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", className = "hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.NoopType")
    @ResponseWrapper(localName = "NoopResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", className = "hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.NoopResponseType")
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/Noop", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/NoopResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/Noop/Fault/MessageFaultMsg")
    })
    public String noop()
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherResponseType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "GetVoucher", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetVoucher")
    @WebResult(name = "VoucherResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetVoucher", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetVoucherResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetVoucher/Fault/MessageFaultMsg")
    })
    public VoucherResponseType getVoucher(
        @WebParam(name = "getVoucher", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        GetVoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "ModifyVoucher", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/ModifyVoucher")
    @WebResult(name = "VoucherACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/ModifyVoucher", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/ModifyVoucherResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/ModifyVoucher/Fault/MessageFaultMsg")
    })
    public VoucherACKType modifyVoucher(
        @WebParam(name = "modifyVoucher", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        UpdVoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "CancelVoucher", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/CancelVoucher")
    @WebResult(name = "VoucherACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/CancelVoucher", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/CancelVoucherResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/CancelVoucher/Fault/MessageFaultMsg")
    })
    public VoucherACKType cancelVoucher(
        @WebParam(name = "cancelVoucher", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        CancelVoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKPostType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "AddRemission", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/AddRemission")
    @WebResult(name = "RemissionResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/AddRemission", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/AddRemissionResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/AddRemission/Fault/MessageFaultMsg")
    })
    public VoucherACKPostType addRemission(
        @WebParam(name = "addRemission", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        RemissionType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKPostType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "GetRemission", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetRemission")
    @WebResult(name = "RemissionResponse", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetRemission", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetRemissionResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetRemission/Fault/MessageFaultMsg")
    })
    public VoucherACKPostType getRemission(
        @WebParam(name = "getRemission", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        GetVoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "ModifyRemission", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/ModifyRemission")
    @WebResult(name = "RemissionACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/ModifyRemission", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/ModifyRemissionResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/ModifyRemission/Fault/MessageFaultMsg")
    })
    public VoucherACKType modifyRemission(
        @WebParam(name = "modifyRemission", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        UpdRemissionType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.VoucherACKType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "CancelRemission", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/CancelRemission")
    @WebResult(name = "RemissionACK", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/CancelRemission", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/CancelRemissionResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/CancelRemission/Fault/MessageFaultMsg")
    })
    public VoucherACKType cancelRemission(
        @WebParam(name = "cancelRemission", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        CancelVoucherType body)
        throws MessageFaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns hn.com.tigo.equipmentaccessoriesbilling.services.basicvoucherservice.RemissionType
     * @throws MessageFaultMsg
     */
    @WebMethod(operationName = "GetRemissionDEI", action = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetRemissionDEI")
    @WebResult(name = "RemissionDEI_Response", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/GetRemissionDEI", output = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetRemissionDEIResponse", fault = {
        @FaultAction(className = MessageFaultMsg.class, value = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/BasicVoucherPort/GetRemissionDEI/Fault/MessageFaultMsg")
    })
    public RemissionType getRemissionDEI(
        @WebParam(name = "getRemissionDEI", targetNamespace = "http://www.tigo.com/ElectronicBilling/Service/Voucher/v1/schema", partName = "body")
        GetRemissionDEI body)
        throws MessageFaultMsg
    ;

}
