
package hn.com.tigo.equipmentinsurance.services.executeorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Order", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Order {


    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "loanProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.LoanProduct")
    @ResponseWrapper(localName = "loanProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.LoanProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/loanProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/loanProductResponse")
    public OrderResponse loanProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "sellProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.SellProduct")
    @ResponseWrapper(localName = "sellProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.SellProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/sellProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/sellProductResponse")
    public OrderResponse sellProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "deactivateProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.DeactivateProduct")
    @ResponseWrapper(localName = "deactivateProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.DeactivateProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/deactivateProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/deactivateProductResponse")
    public OrderResponse deactivateProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "purchaseProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.PurchaseProduct")
    @ResponseWrapper(localName = "purchaseProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.PurchaseProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/purchaseProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/purchaseProductResponse")
    public OrderResponse purchaseProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "transferProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.TransferProduct")
    @ResponseWrapper(localName = "transferProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.TransferProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/transferProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/transferProductResponse")
    public OrderResponse transferProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

    /**
     * 
     * @param simpleOrderRequest
     * @return
     *     returns hn.com.tigo.equipmentinsurance.services.executeorder.OrderResponse
     */
    @WebMethod
    @WebResult(name = "simpleOrderResponse", targetNamespace = "")
    @RequestWrapper(localName = "activateProduct", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.ActivateProduct")
    @ResponseWrapper(localName = "activateProductResponse", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1", className = "hn.com.tigo.equipmentinsurance.services.executeorder.ActivateProductResponse")
    @Action(input = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/activateProductRequest", output = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1/Order/activateProductResponse")
    public OrderResponse activateProduct(
        @WebParam(name = "simpleOrderRequest", targetNamespace = "http://tigo.com/josm/gateway/services/order/SimpleOrderRequest/V1")
        SimpleOrderRequest simpleOrderRequest);

}
