
package hn.com.tigo.jteller.services.soap.cbsquery.customer.info;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CBSQueryCustomerInfoTask", targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CBSQueryCustomerInfoTask {


    /**
     * 
     * @param arg0
     * @return
     *     returns hn.com.tigo.jteller.services.soap.cbsquery.customer.info.TaskResponseType
     * @throws AdapterException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeTask", targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", className = "hn.com.tigo.jteller.services.soap.cbsquery.customer.info.ExecuteTask")
    @ResponseWrapper(localName = "executeTaskResponse", targetNamespace = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/", className = "hn.com.tigo.jteller.services.soap.cbsquery.customer.info.ExecuteTaskResponse")
    @Action(input = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/CBSQueryCustomerInfoTask/executeTaskRequest", output = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/CBSQueryCustomerInfoTask/executeTaskResponse", fault = {
        @FaultAction(className = AdapterException_Exception.class, value = "http://task.cbs2.adapter.orchestrator.josm.tigo.com.hn/CBSQueryCustomerInfoTask/executeTask/Fault/AdapterException")
    })
    public TaskResponseType executeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        TaskRequestType arg0)
        throws AdapterException_Exception
    ;

}
